# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'MyProject' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyProject

pod 'AFNetworking', '3.1.0'
pod "FBSDKCoreKit", "4.1.0", :inhibit_warnings => true     # FaceBook SDK for Corekit
pod "FBSDKLoginKit", "4.1.0", :inhibit_warnings => true    # FaceBook SDK for Social Login
pod "FBSDKShareKit", "4.1.0", :inhibit_warnings => true    # FaceBook SDK for ShareKit

end
